//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int ID { get; set; }
        public string OrderItemID { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public int OrderID { get; set; }
        public int PartID { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Parts Parts { get; set; }
    }
}
