//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parts()
        {
            this.OrderItem = new HashSet<OrderItem>();
        }
    
        public int ID { get; set; }
        public string PartID { get; set; }
        public string PartName { get; set; }
        public string PartDescription { get; set; }
        public decimal UnitPrice { get; set; }
        public byte[] PartImage { get; set; }
        public int SubCID { get; set; }
        public int SupplierID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
